# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AggPoly
                                 A QGIS plugin
 Aggregation of polygons within a certain distance and taking barriers into account.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-11-06
        copyright            : (C) 2019 by Friedrich Viedt
        email                : ***REMOVED***
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Friedrich Viedt'
__date__ = '2019-11-06'
__copyright__ = '(C) 2019 by Friedrich Viedt'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AggPoly class from file AggPoly.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .agg_poly import AggPolyPlugin
    return AggPolyPlugin()
